import { NextResponse } from 'next/server'

// TODO: Replace with database queries with filtering, sorting, and pagination
// TODO: Add query params: ?lifecycle=Emerging&urgency_min=7&sort=composite_score
// TODO: Add full-text search across title and description
export async function GET() {
  const problems = [
    {
      id: 'prob-001',
      title: 'Cross-Border Estate Tax Exposure',
      description:
        'UHNW families with assets in 3+ jurisdictions face conflicting estate tax regimes, creating $2M-$15M unexpected liabilities upon generational transfer.',
      wealth_tier: 'UHNW ($30M+)',
      pain_category: 'Wealth Preservation',
      lifecycle_stage: 'Accelerating',
      urgency_score: 9.2,
      credibility_score: 8.7,
      wtp_signal: 'High',
      composite_score: 91,
      wtp_range: '$50K-$250K/year',
      citation_count: 14,
      buyer_type: 'Family Office CIO',
      compliance_risk: 'High',
      trust_channel: 'Trusted Advisor Referral',
      source_types: ['Industry Report', 'Regulatory Filing', 'Expert Interview'],
      created_at: '2025-12-15T10:00:00Z',
      is_new: false,
    },
    {
      id: 'prob-002',
      title: 'Cybersecurity for Family Office Infrastructure',
      description:
        'Family offices are 3x more likely to be targeted by sophisticated cyber attacks than institutional peers, with average breach cost of $4.2M and reputational damage.',
      wealth_tier: 'UHNW ($30M+)',
      pain_category: 'Risk & Security',
      lifecycle_stage: 'Proven',
      urgency_score: 8.8,
      credibility_score: 9.1,
      wtp_signal: 'High',
      composite_score: 89,
      wtp_range: '$75K-$300K/year',
      citation_count: 19,
      buyer_type: 'Family Office COO',
      compliance_risk: 'Critical',
      trust_channel: 'Peer Network',
      source_types: ['FBI Alert', 'Deloitte Report', 'IC3 Data'],
      created_at: '2025-11-20T08:30:00Z',
      is_new: false,
    },
    {
      id: 'prob-003',
      title: 'Next-Gen Wealth Transfer Readiness Gap',
      description:
        'Only 22% of HNW families have a formalized succession plan. $84T wealth transfer expected by 2045, with 70% of transitions failing to preserve family wealth.',
      wealth_tier: 'HNW ($5M-$30M)',
      pain_category: 'Legacy & Succession',
      lifecycle_stage: 'Accelerating',
      urgency_score: 8.5,
      credibility_score: 8.9,
      wtp_signal: 'High',
      composite_score: 87,
      wtp_range: '$25K-$150K/engagement',
      citation_count: 22,
      buyer_type: 'Patriarch/Matriarch',
      compliance_risk: 'Medium',
      trust_channel: 'Trusted Advisor Referral',
      source_types: ['UBS Report', 'Capgemini WWR', 'Academic Study'],
      created_at: '2026-01-05T14:20:00Z',
      is_new: false,
    },
    {
      id: 'prob-004',
      title: 'AI-Driven Investment Fraud Targeting HNW',
      description:
        'Deepfake-powered investment scams targeting HNW individuals rose 340% in 2025. Average loss per incident: $1.8M. Traditional KYC/AML tools miss 60% of these attacks.',
      wealth_tier: 'HNW ($5M-$30M)',
      pain_category: 'Risk & Security',
      lifecycle_stage: 'Emerging',
      urgency_score: 9.5,
      credibility_score: 7.6,
      wtp_signal: 'Very High',
      composite_score: 86,
      wtp_range: '$40K-$200K/year',
      citation_count: 8,
      buyer_type: 'Wealth Manager',
      compliance_risk: 'Critical',
      trust_channel: 'Industry Conference',
      source_types: ['FBI Alert', 'FTC Press Release', 'IC3 Report'],
      created_at: '2026-03-28T09:15:00Z',
      is_new: true,
    },
    {
      id: 'prob-005',
      title: 'Illiquid Alternative Asset Valuation Opacity',
      description:
        'HNW portfolios with 30-60% alternatives lack real-time valuation. Quarter-end NAV discrepancies average 12%, causing tax miscalculations and trust accounting errors.',
      wealth_tier: 'UHNW ($30M+)',
      pain_category: 'Portfolio Management',
      lifecycle_stage: 'Proven',
      urgency_score: 7.4,
      credibility_score: 8.3,
      wtp_signal: 'Medium',
      composite_score: 78,
      wtp_range: '$30K-$120K/year',
      citation_count: 11,
      buyer_type: 'Family Office CIO',
      compliance_risk: 'Medium',
      trust_channel: 'Peer Network',
      source_types: ['Industry Report', 'Citi Wealth Report'],
      created_at: '2025-10-12T11:45:00Z',
      is_new: false,
    },
    {
      id: 'prob-006',
      title: 'Philanthropic Impact Measurement Deficit',
      description:
        'Next-gen HNW donors demand measurable impact but 78% of family foundations lack standardized impact metrics. Donor-advised fund inflows stalling without accountability.',
      wealth_tier: 'HNW ($5M-$30M)',
      pain_category: 'Philanthropy & Impact',
      lifecycle_stage: 'Emerging',
      urgency_score: 6.8,
      credibility_score: 7.5,
      wtp_signal: 'Medium',
      composite_score: 71,
      wtp_range: '$15K-$75K/year',
      citation_count: 9,
      buyer_type: 'Next-Gen Principal',
      compliance_risk: 'Low',
      trust_channel: 'Thought Leadership',
      source_types: ['McKinsey Insights', 'Academic Study'],
      created_at: '2026-03-30T16:00:00Z',
      is_new: true,
    },
    {
      id: 'prob-007',
      title: 'Regulatory Fragmentation in Digital Assets',
      description:
        'HNW investors holding crypto/tokenized assets face 14+ conflicting regulatory frameworks globally. Compliance cost per jurisdiction: $50K-$200K annually.',
      wealth_tier: 'UHNW ($30M+)',
      pain_category: 'Regulatory & Compliance',
      lifecycle_stage: 'Accelerating',
      urgency_score: 8.1,
      credibility_score: 7.9,
      wtp_signal: 'High',
      composite_score: 82,
      wtp_range: '$60K-$250K/year',
      citation_count: 16,
      buyer_type: 'Family Office GC',
      compliance_risk: 'Critical',
      trust_channel: 'Legal Network',
      source_types: ['Regulatory Filing', 'Industry Report', 'Expert Interview'],
      created_at: '2026-02-18T13:30:00Z',
      is_new: false,
    },
    {
      id: 'prob-008',
      title: 'Concierge Health Access Inequality',
      description:
        'HNW families in secondary markets lack access to elite concierge medicine networks. Wait times for specialist referrals 4x longer than metro UHNW peers.',
      wealth_tier: 'HNW ($5M-$30M)',
      pain_category: 'Lifestyle & Wellness',
      lifecycle_stage: 'Saturated',
      urgency_score: 5.9,
      credibility_score: 6.8,
      wtp_signal: 'Low',
      composite_score: 58,
      wtp_range: '$10K-$50K/year',
      citation_count: 5,
      buyer_type: 'HNW Individual',
      compliance_risk: 'Low',
      trust_channel: 'Peer Network',
      source_types: ['PubMed', 'Industry Report'],
      created_at: '2025-08-22T09:00:00Z',
      is_new: false,
    },
  ]

  return NextResponse.json(problems)
}
