import { NextRequest, NextResponse } from 'next/server'

// Full mock dataset — 47 problems across wealth tiers and pain categories
const ALL_PROBLEMS = [
  {
    id: 'prob-001',
    title: 'Cross-Border Estate Tax Exposure',
    description: 'UHNW families with assets in 3+ jurisdictions face conflicting estate tax regimes, creating $2M-$15M unexpected liabilities upon generational transfer.',
    wealth_tier: 'UHNW ($30M+)',
    pain_category: 'Wealth Preservation',
    lifecycle_stage: 'Accelerating',
    urgency_score: 9.2,
    credibility_score: 8.7,
    wtp_signal: 'High',
    composite_score: 91,
    wtp_range: '$50K-$250K/year',
    citation_count: 14,
    buyer_type: 'Family Office CIO',
    compliance_risk: 'High',
    trust_channel: 'Trusted Advisor Referral',
    source_types: ['Industry Report', 'Regulatory Filing', 'Expert Interview'],
    created_at: '2025-12-15T10:00:00Z',
    is_new: false,
  },
  {
    id: 'prob-002',
    title: 'Cybersecurity for Family Office Infrastructure',
    description: 'Family offices are 3x more likely to be targeted by sophisticated cyber attacks than institutional peers, with average breach cost of $4.2M and reputational damage.',
    wealth_tier: 'UHNW ($30M+)',
    pain_category: 'Risk & Security',
    lifecycle_stage: 'Proven',
    urgency_score: 8.8,
    credibility_score: 9.1,
    wtp_signal: 'High',
    composite_score: 89,
    wtp_range: '$75K-$300K/year',
    citation_count: 19,
    buyer_type: 'Family Office COO',
    compliance_risk: 'Critical',
    trust_channel: 'Peer Network',
    source_types: ['FBI Alert', 'Deloitte Report', 'IC3 Data'],
    created_at: '2025-11-20T08:30:00Z',
    is_new: false,
  },
  {
    id: 'prob-003',
    title: 'Next-Gen Wealth Transfer Readiness Gap',
    description: 'Only 22% of HNW families have a formalized succession plan. $84T wealth transfer expected by 2045, with 70% of transitions failing to preserve family wealth.',
    wealth_tier: 'HNW ($5M-$30M)',
    pain_category: 'Legacy & Succession',
    lifecycle_stage: 'Accelerating',
    urgency_score: 8.5,
    credibility_score: 8.9,
    wtp_signal: 'High',
    composite_score: 87,
    wtp_range: '$25K-$150K/engagement',
    citation_count: 22,
    buyer_type: 'Patriarch/Matriarch',
    compliance_risk: 'Medium',
    trust_channel: 'Trusted Advisor Referral',
    source_types: ['UBS Report', 'Capgemini WWR', 'Academic Study'],
    created_at: '2026-01-05T14:20:00Z',
    is_new: false,
  },
  {
    id: 'prob-004',
    title: 'AI-Driven Investment Fraud Targeting HNW',
    description: 'Deepfake-powered investment scams targeting HNW individuals rose 340% in 2025. Average loss per incident: $1.8M. Traditional KYC/AML tools miss 60% of these attacks.',
    wealth_tier: 'HNW ($5M-$30M)',
    pain_category: 'Risk & Security',
    lifecycle_stage: 'Emerging',
    urgency_score: 9.5,
    credibility_score: 7.6,
    wtp_signal: 'Very High',
    composite_score: 86,
    wtp_range: '$40K-$200K/year',
    citation_count: 8,
    buyer_type: 'Wealth Manager',
    compliance_risk: 'Critical',
    trust_channel: 'Industry Conference',
    source_types: ['FBI Alert', 'FTC Press Release', 'IC3 Report'],
    created_at: '2026-03-28T09:15:00Z',
    is_new: true,
  },
  {
    id: 'prob-005',
    title: 'Illiquid Alternative Asset Valuation Opacity',
    description: 'HNW portfolios with 30-60% alternatives lack real-time valuation. Quarter-end NAV discrepancies average 12%, causing tax miscalculations and trust accounting errors.',
    wealth_tier: 'UHNW ($30M+)',
    pain_category: 'Portfolio Management',
    lifecycle_stage: 'Proven',
    urgency_score: 7.4,
    credibility_score: 8.3,
    wtp_signal: 'Medium',
    composite_score: 78,
    wtp_range: '$30K-$120K/year',
    citation_count: 11,
    buyer_type: 'Family Office CIO',
    compliance_risk: 'Medium',
    trust_channel: 'Peer Network',
    source_types: ['Industry Report', 'Citi Wealth Report'],
    created_at: '2025-10-12T11:45:00Z',
    is_new: false,
  },
  {
    id: 'prob-006',
    title: 'Philanthropic Impact Measurement Deficit',
    description: 'Next-gen HNW donors demand measurable impact but 78% of family foundations lack standardized impact metrics. Donor-advised fund inflows stalling without accountability.',
    wealth_tier: 'HNW ($5M-$30M)',
    pain_category: 'Philanthropy & Impact',
    lifecycle_stage: 'Emerging',
    urgency_score: 6.8,
    credibility_score: 7.5,
    wtp_signal: 'Medium',
    composite_score: 71,
    wtp_range: '$15K-$75K/year',
    citation_count: 9,
    buyer_type: 'Next-Gen Principal',
    compliance_risk: 'Low',
    trust_channel: 'Thought Leadership',
    source_types: ['McKinsey Insights', 'Academic Study'],
    created_at: '2026-03-30T16:00:00Z',
    is_new: true,
  },
  {
    id: 'prob-007',
    title: 'Regulatory Fragmentation in Digital Assets',
    description: 'HNW investors holding crypto/tokenized assets face 14+ conflicting regulatory frameworks globally. Compliance cost per jurisdiction: $50K-$200K annually.',
    wealth_tier: 'UHNW ($30M+)',
    pain_category: 'Regulatory & Compliance',
    lifecycle_stage: 'Accelerating',
    urgency_score: 8.1,
    credibility_score: 7.9,
    wtp_signal: 'High',
    composite_score: 82,
    wtp_range: '$60K-$250K/year',
    citation_count: 16,
    buyer_type: 'Family Office GC',
    compliance_risk: 'Critical',
    trust_channel: 'Legal Network',
    source_types: ['Regulatory Filing', 'Industry Report', 'Expert Interview'],
    created_at: '2026-02-18T13:30:00Z',
    is_new: false,
  },
  {
    id: 'prob-008',
    title: 'Concierge Health Access Inequality',
    description: 'HNW families in secondary markets lack access to elite concierge medicine networks. Wait times for specialist referrals 4x longer than metro UHNW peers.',
    wealth_tier: 'HNW ($5M-$30M)',
    pain_category: 'Lifestyle & Wellness',
    lifecycle_stage: 'Saturated',
    urgency_score: 5.9,
    credibility_score: 6.8,
    wtp_signal: 'Low',
    composite_score: 58,
    wtp_range: '$10K-$50K/year',
    citation_count: 5,
    buyer_type: 'HNW Individual',
    compliance_risk: 'Low',
    trust_channel: 'Peer Network',
    source_types: ['PubMed', 'Industry Report'],
    created_at: '2025-08-22T09:00:00Z',
    is_new: false,
  },
  // ── Additional 39 problems to reach 47 total ──
  { id: 'prob-009', title: 'Private Aviation Safety Compliance Gaps', description: 'UHNW families operating fractional or whole-ownership aircraft face evolving FAA Part 91 mandates. 40% of private operators have at least one open safety finding.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Risk & Security', lifecycle_stage: 'Proven', urgency_score: 7.2, credibility_score: 8.0, wtp_signal: 'Medium', composite_score: 76, wtp_range: '$20K-$80K/year', citation_count: 7, buyer_type: 'Family Office COO', compliance_risk: 'High', trust_channel: 'Peer Network', source_types: ['FAA Report', 'Industry Report'], created_at: '2025-09-10T10:00:00Z', is_new: false },
  { id: 'prob-010', title: 'Trust Protector Selection & Oversight Gaps', description: 'Irrevocable trusts worth $50M+ increasingly need independent trust protectors. Only 15% of families conduct formal due diligence on protector candidates.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Legacy & Succession', lifecycle_stage: 'Emerging', urgency_score: 7.8, credibility_score: 7.4, wtp_signal: 'High', composite_score: 77, wtp_range: '$25K-$100K/year', citation_count: 6, buyer_type: 'Estate Attorney', compliance_risk: 'Medium', trust_channel: 'Legal Network', source_types: ['Academic Study', 'Expert Interview'], created_at: '2026-01-22T09:00:00Z', is_new: false },
  { id: 'prob-011', title: 'Domestic Staff Employment Liability', description: 'HNW households with 5+ domestic staff face $200K+ annual employment law exposure. Wage-and-hour claims against private employers up 28% since 2024.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Regulatory & Compliance', lifecycle_stage: 'Accelerating', urgency_score: 7.1, credibility_score: 7.6, wtp_signal: 'Medium', composite_score: 73, wtp_range: '$12K-$28K/mo', citation_count: 8, buyer_type: 'HNW Individual', compliance_risk: 'High', trust_channel: 'Trusted Advisor Referral', source_types: ['DOL Report', 'Legal Brief'], created_at: '2025-11-05T14:00:00Z', is_new: false },
  { id: 'prob-012', title: 'Family Office Talent Retention Crisis', description: 'Average tenure for SFO key person roles dropped to 2.4 years. 55% of family offices lost at least one senior hire to institutional firms in 2025.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Portfolio Management', lifecycle_stage: 'Accelerating', urgency_score: 8.0, credibility_score: 7.8, wtp_signal: 'High', composite_score: 80, wtp_range: '$40K-$150K/year', citation_count: 12, buyer_type: 'Family Office COO', compliance_risk: 'Low', trust_channel: 'Peer Network', source_types: ['Campden Wealth', 'Industry Survey'], created_at: '2026-02-01T08:00:00Z', is_new: false },
  { id: 'prob-013', title: 'Insurance Portfolio Fragmentation', description: 'UHNW families with 5+ properties average 14 separate policies with 23% coverage overlap and 18% gap exposure. Premium waste averages $120K/year.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Risk & Security', lifecycle_stage: 'Proven', urgency_score: 6.9, credibility_score: 8.1, wtp_signal: 'Medium', composite_score: 74, wtp_range: '$10K-$25K/mo', citation_count: 9, buyer_type: 'Family Office COO', compliance_risk: 'Medium', trust_channel: 'Trusted Advisor Referral', source_types: ['Marsh Report', 'Industry Report'], created_at: '2025-10-28T11:00:00Z', is_new: false },
  { id: 'prob-014', title: 'Art Collection Provenance & Insurance Risk', description: 'HNW art collectors face $500K+ uninsured losses from provenance disputes. Only 30% of collections over $5M have comprehensive title insurance.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Wealth Preservation', lifecycle_stage: 'Saturated', urgency_score: 5.8, credibility_score: 7.2, wtp_signal: 'Medium', composite_score: 64, wtp_range: '$15K-$60K/year', citation_count: 4, buyer_type: 'HNW Individual', compliance_risk: 'Low', trust_channel: 'Peer Network', source_types: ['ArtTactic', 'Industry Report'], created_at: '2025-07-15T10:00:00Z', is_new: false },
  { id: 'prob-015', title: 'Multi-Jurisdictional Tax Reporting Burden', description: 'UHNW families with residences in 3+ countries spend average $350K annually on tax compliance. 62% report at least one filing error per year.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Regulatory & Compliance', lifecycle_stage: 'Proven', urgency_score: 7.6, credibility_score: 8.5, wtp_signal: 'High', composite_score: 81, wtp_range: '$50K-$200K/year', citation_count: 15, buyer_type: 'Family Office GC', compliance_risk: 'Critical', trust_channel: 'Legal Network', source_types: ['EY Report', 'Regulatory Filing'], created_at: '2026-01-10T12:00:00Z', is_new: false },
  { id: 'prob-016', title: 'Family Governance Framework Absence', description: '80% of multigenerational families lack formal governance. Families without a charter are 3x more likely to experience destructive conflict during transitions.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Legacy & Succession', lifecycle_stage: 'Accelerating', urgency_score: 7.9, credibility_score: 8.2, wtp_signal: 'High', composite_score: 80, wtp_range: '$20K-$80K/engagement', citation_count: 18, buyer_type: 'Patriarch/Matriarch', compliance_risk: 'Low', trust_channel: 'Trusted Advisor Referral', source_types: ['FFI Study', 'Academic Study'], created_at: '2026-02-14T09:30:00Z', is_new: false },
  { id: 'prob-017', title: 'Private Equity Co-Investment Due Diligence Gap', description: 'HNW investors entering PE co-investments average 40% less due diligence than institutional LPs. Default rate on under-diligenced deals: 3.2x higher.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Portfolio Management', lifecycle_stage: 'Emerging', urgency_score: 7.3, credibility_score: 7.7, wtp_signal: 'Medium', composite_score: 75, wtp_range: '$30K-$100K/deal', citation_count: 7, buyer_type: 'Wealth Manager', compliance_risk: 'Medium', trust_channel: 'Industry Conference', source_types: ['Preqin Data', 'Expert Interview'], created_at: '2026-03-05T15:00:00Z', is_new: false },
  { id: 'prob-018', title: 'Yacht & Vessel Regulatory Compliance', description: 'Superyacht owners face ISM/ISPS code requirements, flag state audits, and MLC crew standards. Average annual compliance cost: $180K for 40m+ vessels.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Regulatory & Compliance', lifecycle_stage: 'Saturated', urgency_score: 5.5, credibility_score: 7.0, wtp_signal: 'Low', composite_score: 60, wtp_range: '$15K-$50K/year', citation_count: 4, buyer_type: 'HNW Individual', compliance_risk: 'Medium', trust_channel: 'Peer Network', source_types: ['IMO Report', 'Industry Report'], created_at: '2025-06-20T10:00:00Z', is_new: false },
  { id: 'prob-019', title: 'Wealth Advisor Conflict of Interest Exposure', description: '45% of HNW clients cannot identify their advisors compensation structure. Undisclosed conflicts cost clients an estimated 1.2% in annual returns.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Portfolio Management', lifecycle_stage: 'Accelerating', urgency_score: 7.5, credibility_score: 8.0, wtp_signal: 'Medium', composite_score: 77, wtp_range: '$15K-$60K/year', citation_count: 11, buyer_type: 'HNW Individual', compliance_risk: 'High', trust_channel: 'Thought Leadership', source_types: ['SEC Filing', 'Academic Study'], created_at: '2025-12-01T13:00:00Z', is_new: false },
  { id: 'prob-020', title: 'Real Estate Portfolio Climate Risk', description: 'Coastal and wildfire-zone properties held by UHNW families face 15-30% value at risk from climate events. Insurance availability declining in key markets.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Risk & Security', lifecycle_stage: 'Accelerating', urgency_score: 8.2, credibility_score: 8.4, wtp_signal: 'High', composite_score: 83, wtp_range: '$25K-$100K/year', citation_count: 13, buyer_type: 'Family Office CIO', compliance_risk: 'Medium', trust_channel: 'Industry Conference', source_types: ['FEMA Data', 'McKinsey Report'], created_at: '2026-03-01T10:00:00Z', is_new: true },
  { id: 'prob-021', title: 'Digital Identity Theft Escalation', description: 'Synthetic identity fraud targeting HNW individuals rose 280% in 2025. Average remediation cost: $850K including legal and reputational damage.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Risk & Security', lifecycle_stage: 'Emerging', urgency_score: 9.0, credibility_score: 7.8, wtp_signal: 'Very High', composite_score: 85, wtp_range: '$15K-$40K/mo', citation_count: 10, buyer_type: 'HNW Individual', compliance_risk: 'High', trust_channel: 'Peer Network', source_types: ['FTC Report', 'Experian Data'], created_at: '2026-03-20T08:00:00Z', is_new: true },
  { id: 'prob-022', title: 'Family Office Cybersecurity Insurance Gaps', description: 'Only 23% of single family offices carry cyber insurance. Average uninsured loss from ransomware: $3.1M. Carrier appetite shrinking.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Risk & Security', lifecycle_stage: 'Emerging', urgency_score: 8.6, credibility_score: 8.2, wtp_signal: 'High', composite_score: 84, wtp_range: '$20K-$80K/year', citation_count: 11, buyer_type: 'Family Office COO', compliance_risk: 'Critical', trust_channel: 'Industry Conference', source_types: ['Aon Report', 'IC3 Data'], created_at: '2026-02-28T11:00:00Z', is_new: false },
  { id: 'prob-023', title: 'Multigenerational Communication Breakdown', description: '65% of wealth transfer failures attributed to communication failures, not legal or financial planning gaps. G2/G3 engagement declining.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Legacy & Succession', lifecycle_stage: 'Proven', urgency_score: 7.0, credibility_score: 8.3, wtp_signal: 'Medium', composite_score: 76, wtp_range: '$15K-$50K/engagement', citation_count: 14, buyer_type: 'Patriarch/Matriarch', compliance_risk: 'Low', trust_channel: 'Trusted Advisor Referral', source_types: ['Williams Group Study', 'Academic Study'], created_at: '2025-11-15T09:00:00Z', is_new: false },
  { id: 'prob-024', title: 'Direct Indexing Tax Alpha Erosion', description: 'HNW investors using direct indexing strategies see tax-loss harvesting alpha decay of 60% after year 3. Few advisors disclose diminishing returns.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Portfolio Management', lifecycle_stage: 'Accelerating', urgency_score: 6.5, credibility_score: 7.9, wtp_signal: 'Medium', composite_score: 72, wtp_range: '$20K-$75K/year', citation_count: 8, buyer_type: 'Wealth Manager', compliance_risk: 'Low', trust_channel: 'Thought Leadership', source_types: ['Vanguard Research', 'Academic Study'], created_at: '2025-12-20T14:00:00Z', is_new: false },
  { id: 'prob-025', title: 'Luxury Property Management Fragmentation', description: 'UHNW families managing 5+ properties spend 15-25 hours/month on vendor coordination. Staff turnover at remote properties averages 45% annually.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Lifestyle & Wellness', lifecycle_stage: 'Proven', urgency_score: 6.7, credibility_score: 7.1, wtp_signal: 'Medium', composite_score: 69, wtp_range: '$10K-$25K/mo', citation_count: 6, buyer_type: 'Family Office COO', compliance_risk: 'Low', trust_channel: 'Peer Network', source_types: ['Industry Survey', 'Expert Interview'], created_at: '2025-09-05T10:00:00Z', is_new: false },
  { id: 'prob-026', title: 'ESG Reporting for Private Holdings', description: 'Family offices with $100M+ PE/RE holdings face mounting LP and regulatory ESG disclosure demands. 70% lack any ESG data collection framework.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Regulatory & Compliance', lifecycle_stage: 'Emerging', urgency_score: 7.4, credibility_score: 7.3, wtp_signal: 'Medium', composite_score: 74, wtp_range: '$30K-$120K/year', citation_count: 9, buyer_type: 'Family Office CIO', compliance_risk: 'High', trust_channel: 'Industry Conference', source_types: ['PRI Report', 'Regulatory Filing'], created_at: '2026-01-15T11:00:00Z', is_new: false },
  { id: 'prob-027', title: 'Travel Security Intelligence Gap', description: 'HNW families traveling to 10+ countries annually lack real-time security intelligence. 35% have experienced a security incident while abroad.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Risk & Security', lifecycle_stage: 'Proven', urgency_score: 7.6, credibility_score: 7.5, wtp_signal: 'High', composite_score: 76, wtp_range: '$8K-$18K/mo', citation_count: 7, buyer_type: 'HNW Individual', compliance_risk: 'Low', trust_channel: 'Peer Network', source_types: ['State Dept Data', 'Expert Interview'], created_at: '2025-10-01T09:00:00Z', is_new: false },
  { id: 'prob-028', title: 'Family Office Technology Stack Obsolescence', description: 'Average SFO runs 8.3 disconnected software tools. Data reconciliation consumes 30% of back-office time. API integration adoption: only 18%.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Portfolio Management', lifecycle_stage: 'Accelerating', urgency_score: 7.0, credibility_score: 7.6, wtp_signal: 'Medium', composite_score: 73, wtp_range: '$25K-$100K/year', citation_count: 10, buyer_type: 'Family Office COO', compliance_risk: 'Low', trust_channel: 'Industry Conference', source_types: ['EY Survey', 'Technology Report'], created_at: '2025-12-10T10:00:00Z', is_new: false },
  { id: 'prob-029', title: 'Concentrated Stock Position Risk', description: 'Executives and founders with 40%+ net worth in single stock face $5M-$50M downside risk. 60% delay diversification due to tax and ego bias.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Portfolio Management', lifecycle_stage: 'Proven', urgency_score: 7.8, credibility_score: 8.6, wtp_signal: 'High', composite_score: 82, wtp_range: '$30K-$150K/engagement', citation_count: 16, buyer_type: 'Wealth Manager', compliance_risk: 'Medium', trust_channel: 'Trusted Advisor Referral', source_types: ['Goldman Sachs', 'Academic Study'], created_at: '2025-11-25T12:00:00Z', is_new: false },
  { id: 'prob-030', title: 'Expatriate Tax Compliance Complexity', description: 'US-connected UHNW families face FATCA, FBAR, and exit tax obligations. IRS audits of international filers up 40% since 2024. Average penalty: $250K.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Regulatory & Compliance', lifecycle_stage: 'Accelerating', urgency_score: 8.3, credibility_score: 8.7, wtp_signal: 'High', composite_score: 84, wtp_range: '$40K-$200K/year', citation_count: 13, buyer_type: 'Family Office GC', compliance_risk: 'Critical', trust_channel: 'Legal Network', source_types: ['IRS Data', 'KPMG Report'], created_at: '2026-02-05T09:00:00Z', is_new: false },
  { id: 'prob-031', title: 'Next-Gen Financial Literacy Deficit', description: 'Only 18% of G2 heirs feel confident managing inherited wealth. 45% report no formal financial education from their family or advisors.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Legacy & Succession', lifecycle_stage: 'Emerging', urgency_score: 6.8, credibility_score: 7.4, wtp_signal: 'Medium', composite_score: 70, wtp_range: '$10K-$30K/mo', citation_count: 8, buyer_type: 'Next-Gen Principal', compliance_risk: 'Low', trust_channel: 'Thought Leadership', source_types: ['Merrill Lynch Study', 'Academic Study'], created_at: '2026-01-28T14:00:00Z', is_new: false },
  { id: 'prob-032', title: 'Charitable Remainder Trust Optimization', description: 'CRTs holding $10M+ assets underperform taxable alternatives by 2.1% annually due to poor asset allocation and trustee inertia.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Philanthropy & Impact', lifecycle_stage: 'Saturated', urgency_score: 5.6, credibility_score: 7.8, wtp_signal: 'Low', composite_score: 63, wtp_range: '$15K-$50K/year', citation_count: 5, buyer_type: 'Estate Attorney', compliance_risk: 'Medium', trust_channel: 'Legal Network', source_types: ['Academic Study', 'IRS Data'], created_at: '2025-08-10T10:00:00Z', is_new: false },
  { id: 'prob-033', title: 'Executive Physical Security Escalation', description: 'Threats against C-suite executives and public-facing founders up 45% since 2024. Only 30% of at-risk individuals have professional security assessments.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Risk & Security', lifecycle_stage: 'Accelerating', urgency_score: 8.4, credibility_score: 7.9, wtp_signal: 'High', composite_score: 82, wtp_range: '$15K-$40K/mo', citation_count: 10, buyer_type: 'HNW Individual', compliance_risk: 'High', trust_channel: 'Peer Network', source_types: ['Secret Service Data', 'Expert Interview'], created_at: '2026-03-12T08:00:00Z', is_new: true },
  { id: 'prob-034', title: 'Impact Investment Measurement Inconsistency', description: 'HNW impact investors face 7+ competing measurement frameworks (IRIS+, GIIRS, SDG). Portfolio-level impact aggregation nearly impossible.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Philanthropy & Impact', lifecycle_stage: 'Emerging', urgency_score: 6.2, credibility_score: 7.1, wtp_signal: 'Medium', composite_score: 67, wtp_range: '$15K-$60K/year', citation_count: 7, buyer_type: 'Next-Gen Principal', compliance_risk: 'Low', trust_channel: 'Thought Leadership', source_types: ['GIIN Report', 'Academic Study'], created_at: '2026-02-20T15:00:00Z', is_new: false },
  { id: 'prob-035', title: 'Private Foundation Compliance Burden', description: 'Private foundations face 5% excise tax risk, self-dealing rules, and minimum distribution requirements. IRS audits of foundations up 35% since 2024.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Regulatory & Compliance', lifecycle_stage: 'Proven', urgency_score: 7.2, credibility_score: 8.4, wtp_signal: 'Medium', composite_score: 77, wtp_range: '$20K-$80K/year', citation_count: 11, buyer_type: 'Family Office GC', compliance_risk: 'High', trust_channel: 'Legal Network', source_types: ['IRS Data', 'EY Report'], created_at: '2025-11-08T11:00:00Z', is_new: false },
  { id: 'prob-036', title: 'Blended Family Estate Planning Complexity', description: 'Second marriages with children from prior relationships create competing inheritance claims. Litigation rates 4x higher than traditional family structures.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Legacy & Succession', lifecycle_stage: 'Accelerating', urgency_score: 7.7, credibility_score: 8.0, wtp_signal: 'High', composite_score: 79, wtp_range: '$20K-$100K/engagement', citation_count: 12, buyer_type: 'Patriarch/Matriarch', compliance_risk: 'Medium', trust_channel: 'Trusted Advisor Referral', source_types: ['ACTEC Study', 'Legal Brief'], created_at: '2026-01-18T09:30:00Z', is_new: false },
  { id: 'prob-037', title: 'Luxury Asset Depreciation Blindspot', description: 'HNW collectors holding $5M+ in watches, cars, and wine often lack mark-to-market tracking. Insurance coverage gaps average 25% of portfolio value.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Wealth Preservation', lifecycle_stage: 'Saturated', urgency_score: 5.4, credibility_score: 6.5, wtp_signal: 'Low', composite_score: 57, wtp_range: '$8K-$30K/year', citation_count: 3, buyer_type: 'HNW Individual', compliance_risk: 'Low', trust_channel: 'Peer Network', source_types: ['Knight Frank Report', 'Industry Report'], created_at: '2025-07-25T10:00:00Z', is_new: false },
  { id: 'prob-038', title: 'Fiduciary Liability for Family Office Principals', description: 'Family office principals making investment decisions for multiple beneficiaries face increasing fiduciary scrutiny. D&O coverage gaps average $5M.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Regulatory & Compliance', lifecycle_stage: 'Emerging', urgency_score: 7.5, credibility_score: 7.6, wtp_signal: 'Medium', composite_score: 75, wtp_range: '$20K-$80K/year', citation_count: 6, buyer_type: 'Family Office GC', compliance_risk: 'High', trust_channel: 'Legal Network', source_types: ['Legal Brief', 'Industry Report'], created_at: '2026-03-08T12:00:00Z', is_new: false },
  { id: 'prob-039', title: 'Social Media Exposure for HNW Children', description: 'Children of HNW families face targeted social engineering via social media. 50% of families have no digital footprint policy for minors.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Risk & Security', lifecycle_stage: 'Emerging', urgency_score: 8.0, credibility_score: 7.2, wtp_signal: 'High', composite_score: 78, wtp_range: '$8K-$20K/mo', citation_count: 6, buyer_type: 'HNW Individual', compliance_risk: 'Medium', trust_channel: 'Peer Network', source_types: ['IC3 Report', 'Expert Interview'], created_at: '2026-03-15T10:00:00Z', is_new: true },
  { id: 'prob-040', title: 'Qualified Opportunity Zone Exit Planning', description: 'HNW investors in QOZ funds face uncertain tax treatment post-2026. $75B deployed with limited exit strategy guidance from fund managers.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Portfolio Management', lifecycle_stage: 'Accelerating', urgency_score: 7.6, credibility_score: 7.8, wtp_signal: 'Medium', composite_score: 76, wtp_range: '$20K-$80K/engagement', citation_count: 9, buyer_type: 'Wealth Manager', compliance_risk: 'High', trust_channel: 'Industry Conference', source_types: ['IRS Guidance', 'Industry Report'], created_at: '2026-02-10T11:00:00Z', is_new: false },
  { id: 'prob-041', title: 'Family Aviation Charter Fraud', description: 'HNW families booking private charters face rising fraud via fake operators. FAA-reported charter fraud incidents up 180% since 2024.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Risk & Security', lifecycle_stage: 'Emerging', urgency_score: 7.8, credibility_score: 7.0, wtp_signal: 'Medium', composite_score: 74, wtp_range: '$8K-$25K/year', citation_count: 5, buyer_type: 'HNW Individual', compliance_risk: 'Medium', trust_channel: 'Peer Network', source_types: ['FAA Alert', 'News Report'], created_at: '2026-03-22T09:00:00Z', is_new: true },
  { id: 'prob-042', title: 'Dynasty Trust Situs Optimization', description: 'Families with $50M+ dynasty trusts can save $2M-$10M by optimizing trust situs across state lines. Only 20% have conducted situs reviews in past 5 years.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Wealth Preservation', lifecycle_stage: 'Proven', urgency_score: 6.8, credibility_score: 8.5, wtp_signal: 'High', composite_score: 78, wtp_range: '$25K-$100K/engagement', citation_count: 10, buyer_type: 'Estate Attorney', compliance_risk: 'Medium', trust_channel: 'Legal Network', source_types: ['ACTEC Study', 'Tax Advisor Report'], created_at: '2025-11-18T14:00:00Z', is_new: false },
  { id: 'prob-043', title: 'Household Cybersecurity Perimeter Failures', description: 'Smart home devices in UHNW residences create 40+ attack vectors. Average household has zero segmented network architecture for IoT.', wealth_tier: 'UHNW ($30M+)', pain_category: 'Risk & Security', lifecycle_stage: 'Accelerating', urgency_score: 8.5, credibility_score: 7.7, wtp_signal: 'High', composite_score: 82, wtp_range: '$10K-$30K/mo', citation_count: 8, buyer_type: 'Family Office COO', compliance_risk: 'High', trust_channel: 'Industry Conference', source_types: ['NIST Report', 'Expert Interview'], created_at: '2026-02-25T10:00:00Z', is_new: false },
  { id: 'prob-044', title: 'Pre-IPO Employee Liquidity Crunch', description: 'Pre-IPO employees with $5M+ in vested stock options face 6-12 month lockups. Secondary market access limited; tax planning windows narrow.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Portfolio Management', lifecycle_stage: 'Accelerating', urgency_score: 7.9, credibility_score: 7.5, wtp_signal: 'High', composite_score: 78, wtp_range: '$20K-$80K/engagement', citation_count: 7, buyer_type: 'Wealth Manager', compliance_risk: 'Medium', trust_channel: 'Industry Conference', source_types: ['Forge Global', 'Expert Interview'], created_at: '2026-03-02T13:00:00Z', is_new: false },
  { id: 'prob-045', title: 'International Custody and Guardianship Planning', description: 'HNW expat families lack cross-border guardianship plans. Legal recognition of guardianship varies by country; 75% have no plan in place.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Legacy & Succession', lifecycle_stage: 'Emerging', urgency_score: 7.1, credibility_score: 7.3, wtp_signal: 'Medium', composite_score: 72, wtp_range: '$15K-$50K/engagement', citation_count: 5, buyer_type: 'Patriarch/Matriarch', compliance_risk: 'Medium', trust_channel: 'Legal Network', source_types: ['Legal Brief', 'Expert Interview'], created_at: '2026-01-30T10:00:00Z', is_new: false },
  { id: 'prob-046', title: 'Donor-Advised Fund Strategic Deployment Gap', description: 'DAFs hold $234B in assets with $160B undeployed. Average payout rate: 22%. Donors lack strategic granting frameworks aligned to impact goals.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Philanthropy & Impact', lifecycle_stage: 'Proven', urgency_score: 6.0, credibility_score: 8.0, wtp_signal: 'Medium', composite_score: 70, wtp_range: '$10K-$40K/year', citation_count: 10, buyer_type: 'Next-Gen Principal', compliance_risk: 'Low', trust_channel: 'Thought Leadership', source_types: ['DAF Report', 'Academic Study'], created_at: '2025-12-05T11:00:00Z', is_new: false },
  { id: 'prob-047', title: 'Longevity Risk and Late-Life Care Planning', description: 'HNW individuals living to 95+ face $2M-$8M in uncovered long-term care costs. LTC insurance market contracting; self-insure strategies poorly structured.', wealth_tier: 'HNW ($5M-$30M)', pain_category: 'Lifestyle & Wellness', lifecycle_stage: 'Accelerating', urgency_score: 7.3, credibility_score: 8.1, wtp_signal: 'Medium', composite_score: 76, wtp_range: '$15K-$60K/year', citation_count: 12, buyer_type: 'Patriarch/Matriarch', compliance_risk: 'Low', trust_channel: 'Trusted Advisor Referral', source_types: ['Genworth Study', 'Industry Report'], created_at: '2026-02-12T09:00:00Z', is_new: false },
]

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams

  const page = parseInt(searchParams.get('page') || '1')
  const limit = parseInt(searchParams.get('limit') || '12')
  const skip = (page - 1) * limit

  const total = ALL_PROBLEMS.length
  const problems = ALL_PROBLEMS.slice(skip, skip + limit)
  const totalPages = Math.ceil(total / limit)

  return NextResponse.json({
    problems,
    pagination: {
      total,
      page,
      limit,
      totalPages,
      hasNext: page < totalPages,
      hasPrev: page > 1,
    },
  })
}
