import { NextRequest, NextResponse } from 'next/server'

const deliverables = [
  {
    id: 'del-001',
    name: 'Incident Response Plan',
    type: 'Security',
    type_color: '#ef4444',
    client_name: 'Wellington Trust',
    client_id: 'cli-001',
    priority: 'critical',
    status: 'overdue',
    sla_date: '2026-04-01',
    sla_status: 'breached',
    sla_days: -2,
    assignee_name: 'Sarah Chen',
    assignee_initials: 'SC',
    qa_score: 3,
    qa_total: 5,
    portal_status: 'pending',
    visionaudio_status: 'complete',
    voiceforge_status: 'scheduled',
    notes: 'Awaiting legal review before final delivery',
    created_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 'del-002',
    name: 'Monthly Report',
    type: 'Report',
    type_color: '#3b82f6',
    client_name: 'Elizabeth Thornton',
    client_id: 'cli-002',
    priority: 'medium',
    status: 'overdue',
    sla_date: '2026-04-02',
    sla_status: 'breached',
    sla_days: -1,
    assignee_name: 'James Miller',
    assignee_initials: 'JM',
    qa_score: 4,
    qa_total: 5,
    portal_status: 'active',
    visionaudio_status: 'complete',
    voiceforge_status: 'complete',
    notes: 'Final charts pending review',
    created_at: '2026-03-20T10:30:00Z',
  },
  {
    id: 'del-003',
    name: 'Household Graph Setup',
    type: 'Onboarding',
    type_color: '#8b5cf6',
    client_name: 'Marcus Reid',
    client_id: 'cli-003',
    priority: 'high',
    status: 'in_progress',
    sla_date: '2026-04-10',
    sla_status: 'on_track',
    sla_days: 7,
    assignee_name: 'Sarah Chen',
    assignee_initials: 'SC',
    qa_score: 2,
    qa_total: 5,
    portal_status: 'pending',
    visionaudio_status: 'in_progress',
    voiceforge_status: 'not_started',
    notes: 'Week 2 of 8 — mapping family entities',
    created_at: '2026-03-18T14:00:00Z',
  },
  {
    id: 'del-004',
    name: 'Quarterly Investment Review',
    type: 'Report',
    type_color: '#3b82f6',
    client_name: 'Harrington Family Office',
    client_id: 'cli-004',
    priority: 'high',
    status: 'in_review',
    sla_date: '2026-04-07',
    sla_status: 'at_risk',
    sla_days: 4,
    assignee_name: 'David Park',
    assignee_initials: 'DP',
    qa_score: 4,
    qa_total: 5,
    portal_status: 'active',
    visionaudio_status: 'complete',
    voiceforge_status: 'complete',
    notes: 'Alternative allocations section needs update',
    created_at: '2026-03-10T08:00:00Z',
  },
  {
    id: 'del-005',
    name: 'Estate Planning Summary',
    type: 'Legal',
    type_color: '#f59e0b',
    client_name: 'Victoria Ashworth',
    client_id: 'cli-005',
    priority: 'medium',
    status: 'in_progress',
    sla_date: '2026-04-14',
    sla_status: 'on_track',
    sla_days: 11,
    assignee_name: 'James Miller',
    assignee_initials: 'JM',
    qa_score: 3,
    qa_total: 5,
    portal_status: 'pending',
    visionaudio_status: 'not_started',
    voiceforge_status: 'not_started',
    notes: 'Trust structures being finalized with external counsel',
    created_at: '2026-03-22T11:00:00Z',
  },
  {
    id: 'del-006',
    name: 'Risk Assessment Update',
    type: 'Security',
    type_color: '#ef4444',
    client_name: 'Wellington Trust',
    client_id: 'cli-001',
    priority: 'high',
    status: 'in_progress',
    sla_date: '2026-04-08',
    sla_status: 'at_risk',
    sla_days: 5,
    assignee_name: 'Sarah Chen',
    assignee_initials: 'SC',
    qa_score: 2,
    qa_total: 5,
    portal_status: 'pending',
    visionaudio_status: 'in_progress',
    voiceforge_status: 'not_started',
    notes: 'Dependent on Incident Response Plan completion',
    created_at: '2026-03-25T09:30:00Z',
  },
  {
    id: 'del-007',
    name: 'Tax Optimization Strategy',
    type: 'Advisory',
    type_color: '#10b981',
    client_name: 'Elizabeth Thornton',
    client_id: 'cli-002',
    priority: 'medium',
    status: 'complete',
    sla_date: '2026-03-28',
    sla_status: 'met',
    sla_days: 0,
    assignee_name: 'David Park',
    assignee_initials: 'DP',
    qa_score: 5,
    qa_total: 5,
    portal_status: 'delivered',
    visionaudio_status: 'complete',
    voiceforge_status: 'complete',
    notes: 'Delivered on time — client acknowledged receipt',
    created_at: '2026-03-05T10:00:00Z',
  },
  {
    id: 'del-008',
    name: 'Philanthropy Impact Report',
    type: 'Report',
    type_color: '#3b82f6',
    client_name: 'Harrington Family Office',
    client_id: 'cli-004',
    priority: 'low',
    status: 'in_progress',
    sla_date: '2026-04-20',
    sla_status: 'on_track',
    sla_days: 17,
    assignee_name: 'James Miller',
    assignee_initials: 'JM',
    qa_score: 1,
    qa_total: 5,
    portal_status: 'pending',
    visionaudio_status: 'not_started',
    voiceforge_status: 'not_started',
    notes: 'Data collection phase — reaching out to foundation partners',
    created_at: '2026-03-28T13:00:00Z',
  },
  {
    id: 'del-009',
    name: 'Insurance Portfolio Review',
    type: 'Advisory',
    type_color: '#10b981',
    client_name: 'Victoria Ashworth',
    client_id: 'cli-005',
    priority: 'medium',
    status: 'complete',
    sla_date: '2026-03-30',
    sla_status: 'met',
    sla_days: 0,
    assignee_name: 'Sarah Chen',
    assignee_initials: 'SC',
    qa_score: 5,
    qa_total: 5,
    portal_status: 'delivered',
    visionaudio_status: 'complete',
    voiceforge_status: 'complete',
    notes: 'Delivered early — client very satisfied',
    created_at: '2026-03-08T15:00:00Z',
  },
  {
    id: 'del-010',
    name: 'Cybersecurity Audit Checklist',
    type: 'Security',
    type_color: '#ef4444',
    client_name: 'Marcus Reid',
    client_id: 'cli-003',
    priority: 'high',
    status: 'not_started',
    sla_date: '2026-04-18',
    sla_status: 'on_track',
    sla_days: 15,
    assignee_name: 'David Park',
    assignee_initials: 'DP',
    qa_score: 0,
    qa_total: 5,
    portal_status: 'pending',
    visionaudio_status: 'not_started',
    voiceforge_status: 'not_started',
    notes: 'Blocked until onboarding household graph is complete',
    created_at: '2026-03-30T09:00:00Z',
  },
]

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const status = searchParams.get('status')
  const priority = searchParams.get('priority')
  const client_id = searchParams.get('client_id')
  const type = searchParams.get('type')
  const assignee = searchParams.get('assignee')

  let filtered = [...deliverables]

  if (status) {
    filtered = filtered.filter((d) => d.status === status)
  }
  if (priority) {
    filtered = filtered.filter((d) => d.priority === priority)
  }
  if (client_id) {
    filtered = filtered.filter((d) => d.client_id === client_id)
  }
  if (type) {
    filtered = filtered.filter((d) => d.type.toLowerCase() === type.toLowerCase())
  }
  if (assignee) {
    filtered = filtered.filter((d) =>
      d.assignee_name.toLowerCase().includes(assignee.toLowerCase())
    )
  }

  return NextResponse.json(filtered)
}
