import { NextResponse } from 'next/server'

export async function GET() {
  return NextResponse.json([
    {
      id: 'task-001',
      name: 'Finalize Incident Response Plan',
      client_name: 'Wellington Trust',
      priority: 'critical',
      due_at: '2026-04-01T17:00:00Z',
      is_overdue: true,
      days_until: -2,
      is_recurring: false,
      voiceforge_scheduled: true,
      context_note: 'Legal sign-off received — deliver to portal immediately',
    },
    {
      id: 'task-002',
      name: 'Submit Monthly Report',
      client_name: 'Elizabeth Thornton',
      priority: 'medium',
      due_at: '2026-04-02T17:00:00Z',
      is_overdue: true,
      days_until: -1,
      is_recurring: true,
      voiceforge_scheduled: false,
      context_note: 'Charts ready — needs final QA pass before portal upload',
    },
    {
      id: 'task-003',
      name: 'Complete Household Graph mapping',
      client_name: 'Marcus Reid',
      priority: 'high',
      due_at: '2026-04-05T17:00:00Z',
      is_overdue: false,
      days_until: 2,
      is_recurring: false,
      voiceforge_scheduled: false,
      context_note: 'Week 2 milestone — 4 family entities remaining to map',
    },
    {
      id: 'task-004',
      name: 'QA review — Quarterly Investment Review',
      client_name: 'Harrington Family Office',
      priority: 'high',
      due_at: '2026-04-06T12:00:00Z',
      is_overdue: false,
      days_until: 3,
      is_recurring: false,
      voiceforge_scheduled: true,
      context_note: 'Alternative allocations section flagged — verify data sources',
    },
    {
      id: 'task-005',
      name: 'Schedule estate planning call',
      client_name: 'Victoria Ashworth',
      priority: 'medium',
      due_at: '2026-04-08T10:00:00Z',
      is_overdue: false,
      days_until: 5,
      is_recurring: false,
      voiceforge_scheduled: false,
      context_note: 'External counsel available Mon/Wed — coordinate with client EA',
    },
  ])
}
